INTERESTING_INFO_FIELDS <- c("CADD", "CLNSIG", "CLNSIG_MOD", "CSQ", "dbNSFP_GERP___RS", 
                             "dbNSFP_phastCons100way_vertebrate", "dbNSFP_phyloP100way_vertebrate", 
                             "FOO", "gnomAD_mt", "GNOMADAF", "gnomADg", "GNOMADPOP_MAX", "LoFtool", 
                             "loqusdb_freq", "MaxEntScan_alt", "MaxEntScan_diff", "MaxEntScan_ref", 
                             "MES-SWA_acceptor_diff", "MES-SWA_donor_alt", "MES-SWA_donor_diff", 
                             "most_severe_consequence", "phastCons", "RankScore", "REVEL_rankscore", 
                             "REVEL_score", "1KGenomesHeteroplasmy", "1KGenomesHomoplasmy", 
                             "AC", "AF", "AN", "AS_SB_TABLE", "AaChange", "AaVarH", "AaVarP", 
                             "AlleleFreqH", "AlleleFreqH_AF", "AlleleFreqH_AM", "AlleleFreqH_AS", 
                             "AlleleFreqH_EU", "AlleleFreqH_OC", "AlleleFreqP", "AlleleFreqP_AF", 
                             "AlleleFreqP_AM", "AlleleFreqP_AS", "AlleleFreqP_EU", "AlleleFreqP_OC", 
                             "Annotation", "BaseQRankSum", "CLNACC", "CLNREVSTAT", "Clinvar", 
                             "ClippingRankSum", "Compounds", "DP", "DiseaseScore", "ECNT", 
                             "ExcessHet", "FS", "GNOMADAF_MAX", "GeneticModels", "HmtVar", 
                             "Locus", "MBQ", "MFRL", "MLEAC", "MLEAF", "MMQ", "MPOS", "MQ", 
                             "MQRankSum", "MitomapAssociatedDiseases", "MitomapHeteroplasmy", 
                             "MitomapHomoplasmy", "MitomapSomaticMutations", "ModelScore", 
                             "MutPred_Prediction", "MutPred_Probability", "NtVarH", "NtVarP", 
                             "OCM", "OMIM", "POPAF", "Panther_Prediction", "Panther_Probability", 
                             "Pathogenicity", "PhDSNP_Prediction", "PhDSNP_Probability", "Polyphen2HumDiv_Prediction", 
                             "Polyphen2HumDiv_Probability", "Polyphen2HumVar_Prediction", 
                             "Polyphen2HumVar_Probability", "QD", "RankResult", "ReadPosRankSum", 
                             "SNPsGO_Prediction", "SNPsGO_Probability", "SOR", "SPLICE_INDEL", 
                             "SomaticMutationsHeteroplasmy", "SomaticMutationsHomoplasmy", 
                             "TLOD", "dbSNP")

MITO_ONLY_INFO_FIELDS <- c("1KGenomesHeteroplasmy", "1KGenomesHomoplasmy", "AaChange", 
                          "AaVarH", "AaVarP", "AlleleFreqH", "AlleleFreqH_AF", "AlleleFreqH_AM", 
                          "AlleleFreqH_AS", "AlleleFreqH_EU", "AlleleFreqH_OC", "AlleleFreqP", 
                          "AlleleFreqP_AF", "AlleleFreqP_AM", "AlleleFreqP_AS", "AlleleFreqP_EU", 
                          "AlleleFreqP_OC", "AS_SB_TABLE", "Clinvar", "dbSNP", "DiseaseScore", 
                          "ECNT", "HmtVar", "Locus", "MBQ", "MFRL", "MitomapAssociatedDiseases", 
                          "MitomapHeteroplasmy", "MitomapHomoplasmy", "MitomapSomaticMutations", 
                          "MMQ", "MPOS", "MutPred_Prediction", "MutPred_Probability", "NtVarH", 
                          "NtVarP", "OCM", "OMIM", "Panther_Prediction", "Panther_Probability", 
                          "Pathogenicity", "PhDSNP_Prediction", "PhDSNP_Probability", "Polyphen2HumDiv_Prediction", 
                          "Polyphen2HumDiv_Probability", "Polyphen2HumVar_Prediction", 
                          "Polyphen2HumVar_Probability", "POPAF", "SNPsGO_Prediction", 
                          "SNPsGO_Probability", "SomaticMutationsHeteroplasmy", "SomaticMutationsHomoplasmy", 
                          "TLOD")

CLNSIG_MOD = c(
  '_1_' = "not_provided",
  '_2_' = "benign",
  '_3_' = 'likely_benign',
  '_0_' = 'uncertain_significance',
  '_6_' = "drug_response",
  '_7_' = 'histocompatibility',
  '_255_' = 'other',
  '_4_' = 'likely_pathogenic',
  '_5_' = 'pathogenic'             
)
